from setuptools import setup

setup(name='SpeakEasy-Speeches',
      version='1.0',
      description='SpeakEasy Speeches Website',
      author='Dan Turner',
      author_email='tunafish25@gmail.com',
      url='http://www.python.org/sigs/distutils-sig/',
#     install_requires=['Flask==0.10.1',
#          'sqlalchemy-migrate==0.9.1',
#          'wsgiref==0.1.2'],
#         'Flask-Bcrypt==0.6.0',
#        'Flask-Login==0.2.11',
#         'Flask-SQLAlchemy==1.0',
#         'Flask-WTF==0.9.5',
#         'Jinja2==2.7.3',
#         'Markdown==2.4.1',
#         'MarkupSafe==0.23',
#         'SQLAlchemy==0.9.6',
#         'Tempita==0.5.3dev',
#         'WTForms==1.0.5',
#         'Werkzeug==0.9.6',
#         'argparse==1.2.1',
#         'bleach==1.4',
#         'decorator==3.4.0',
#         'html5lib==1.0b3',
#         'itsdangerous==0.24',
#         'pbr==0.8.2',
#         'py-bcrypt==0.4',
#         'six==1.7.3',
#         'sqlalchemy-migrate==0.9.1',
#          'wsgiref==0.1.2'],
     )
